#!MC 1400
# Created by Tecplot 360 build 14.0.2.33360
#$!VarSet |MFBD| = 'F:\UMN\remote_temp\PA_validation\'
$!VarSet |MFBD| = '/home/plyu/hosmnt/projects/PA/val_if16_nac_2_1/'
#$!VarSet |MFBD| = '/home/pin/LES_HOS_Turbine/new_source_codes/note_LES/runjob/compare_actuator/val_ti0_pitch_1/'

#$!VarSet |OUTDIR|='/home/plyu/temp/'
$!VarSet |OUTDIR|='|MFBD|export/'
$!VarSet |ufric|=(0.102/2.5439)

$!VarSet |NumLoop|=10
$!Loop |NumLoop|
$!VarSet |NewNo|=(21-|Loop|)
$!VarSet |Num|=(|NewNo|*100)

$!VarSet |toverperiod|=(|Num|/100.0)
$!VarSet |ndt|=(|Num|*0.00136225820057*|ufric|/0.46)

$!NEWLAYOUT 

$!READDATASET  '"-F" "1" "|MFBD|DAT_|Num%010d|.h5" "-D" "5" "/pp" "/u" "/v" "/w" "/z" "-I" "-K" "1" "1" "1"'
  DATASETREADER = 'HDF5 Loader'

$!VarSet |NUMVARSINIT| = |NUMVARS|
#$!VarSet |NUMVARSINIT| += 1

$!ALTERDATA 
  EQUATION = '{x1}=({Z})*6.2831853071795862/1.45444104333/384'
$!ALTERDATA 
  EQUATION = '{y1}=({Y})*6.2831853071795862/8.72664625997/96'
$!ALTERDATA 
  EQUATION = '{Z}={/z}'
$!ALTERDATA 
  EQUATION = '{X}={x1}'
$!ALTERDATA 
  EQUATION = '{Y}={y1}'
  
$!VarSet |NUMVARSFIN| = |NUMVARS|
$!DELETEVARS [|NUMVARSINIT|-|NUMVARS|]

$!READDATASET  '"|MFBD|line_|Num%06d|_001_nf.dat" '
  READDATAOPTION = APPEND
  RESETSTYLE = NO
  INCLUDETEXT = NO
  INCLUDEGEOM = NO
  INCLUDECUSTOMLABELS = NO
  VARLOADMODE = BYNAME
  ASSIGNSTRANDIDS = YES
  VARNAMELIST = '"X" "Y" "Z" "/pp" "/u" "/v" "/w" "ub_x" "ub_y" "ub_z" "color" "U_lagr_x" "U_lagr_y" "U_lagr_z" "F_lagr_x" "F_lagr_y" "F_lagr_z"'

$!VarSet |NUMVARSFIN| = |NUMVARS|
$!DELETEVARS [|NUMVARSINIT|-|NUMVARS|]

$!VIEW FIT
$!FIELDLAYERS SHOWMESH = YES
  
$!FIELDMAP [1]  MESH{SHOW = NO}
$!FIELDMAP [1]  SHADE{SHOW = NO}

# define contour_1 variable as 4:pp
$!SETCONTOURVAR 
  VAR = 4
  CONTOURGROUP = 1
  LEVELINITMODE = RESETTONICE
  
# define contour_2 variable as 5:u
$!SETCONTOURVAR 
  VAR = 5
  CONTOURGROUP = 2
  LEVELINITMODE = RESETTONICE
  
# define contour_3 variable as 6:v
$!SETCONTOURVAR 
  VAR = 6
  CONTOURGROUP = 3
  LEVELINITMODE = RESETTONICE
  
# define contour_4 variable as 7:w
$!SETCONTOURVAR 
  VAR = 7
  CONTOURGROUP = 4
  LEVELINITMODE = RESETTONICE
  
# define contour_6 variable as 5:u
$!SETCONTOURVAR 
  VAR = 5
  CONTOURGROUP = 6
  LEVELINITMODE = RESETTONICE
  

$!SLICEATTRIBUTES 1  SHOWGROUP = NO
$!SLICEATTRIBUTES 3  SHOWGROUP = YES
$!SLICEATTRIBUTES 3  CONTOUR{FLOODCOLORING = GROUP2}
$!SLICEATTRIBUTES 3  PRIMARYPOSITION{Z = 0.125}
$!SLICELAYERS SHOW = YES

$!THREEDVIEW VIEWERPOSITION{X = 6.72997215708243601}
$!THREEDVIEW VIEWERPOSITION{Y = -92.6249658557252076}
$!THREEDVIEW VIEWERPOSITION{Z = 75.0161153791101185}
$!THREEDVIEW PSIANGLE = 0
$!THREEDVIEW THETAANGLE = 0

$!VIEW FITSURFACES
#  CONSIDERBLANKING = YES
$!GLOBALCONTOUR 2  COLORMAPFILTER{COLORMAPDISTRIBUTION = CONTINUOUS}
$!GLOBALCONTOUR 2  COLORMAPNAME = 'Diverging - Blue/Red'
$!GLOBALCONTOUR 2  COLORMAPFILTER{CONTINUOUSCOLOR{CMIN = 0.5}}
$!GLOBALCONTOUR 2  COLORMAPFILTER{CONTINUOUSCOLOR{CMAX = 0.900000000000000022}}
$!CONTOURLEVELS NEW
  CONTOURGROUP = 2
  RAWDATA
9
0.5
0.55
0.6
0.65
0.7
0.75
0.8
0.85
0.9

$!GLOBALCONTOUR 2  LEGEND{ISVERTICAL = NO}
$!GLOBALCONTOUR 2  LEGEND{ANCHORALIGNMENT = TOPCENTER}
$!GLOBALCONTOUR 2  LEGEND{BOX{BOXTYPE = NONE}}
$!GLOBALCONTOUR 2  LEGEND{XYPOS{X = 50}}
$!GLOBALCONTOUR 2  LEGEND{XYPOS{Y = 40}}
$!GLOBALCONTOUR 2  LEGEND{NUMBERTEXTSHAPE{HEIGHT = 2}}
$!GLOBALCONTOUR 2  LEGEND{HEADERTEXTSHAPE{HEIGHT = 2}}

$!THREEDVIEW VIEWWIDTH = 4.5
$!THREEDAXIS FRAMEAXIS{SIZE = 6}
$!THREEDAXIS FRAMEAXIS{XYPOS{X = 90}}
$!THREEDAXIS FRAMEAXIS{XYPOS{Y = 32}}

# use blanking
$!BLANKING VALUE{INCLUDE = YES}
$!BLANKING VALUE{CONSTRAINT 1 {INCLUDE = YES}}
$!BLANKING VALUE{CONSTRAINT 1 {RELOP = GREATERTHANOREQUAL}}
$!BLANKING VALUE{CONSTRAINT 1 {VALUECUTOFF = 2.1800000000000002}}
$!SLICEATTRIBUTES 3  OBEYSOURCEZONEBLANKING = YES
$!REDRAWALL 
$!VIEW FITSURFACES
$!THREEDVIEW VIEWWIDTH = 2.25

$!GLOBALCONTOUR 2  LEGEND{XYPOS{Y = 30}}

$!THREEDAXIS FRAMEAXIS{XYPOS{Y = 24}}
$!THREEDAXIS FRAMEAXIS{SIZE = 5.5}

$!ATTACHTEXT
  ANCHORPOS
    {
    X = 5.0
    Y = 27.0
    }
  TEXTSHAPE
    {
    HEIGHT = 14
    ISBOLD = NO
    }
  COLOR = BLACK
  TEXT = 'tu<sub>*</sub>/H=|ndt%.3f|'

$!REDRAWALL 
$!PRINTSETUP PALETTE = COLOR
$!EXPORTSETUP IMAGEWIDTH = 1200
#$!EXPORTSETUP EXPORTFNAME = '|MFBD|export/export_1_xy_ti_|NewNo%05d|.png'
$!EXPORTSETUP EXPORTFNAME = '|OUTDIR|export_1_xy_ti_|NewNo%05d|.png'
$!EXPORT 
  EXPORTREGION = CURRENTFRAME
  
$!SLICEATTRIBUTES 3  SHOWGROUP = NO
$!SLICEATTRIBUTES 2  SHOWGROUP = YES
$!SLICEATTRIBUTES 2  CONTOUR{FLOODCOLORING = GROUP6}
$!SETCONTOURVAR 
  VAR = 5
  CONTOURGROUP = 6
  LEVELINITMODE = RESETTONICE
$!GLOBALCONTOUR 6  COLORMAPFILTER{COLORMAPDISTRIBUTION = CONTINUOUS}
$!THREEDVIEW VIEWERPOSITION{Y = 238.010000000000048}
$!THREEDVIEW VIEWERPOSITION{Z = 144.363750000000039}
$!THREEDVIEW PSIANGLE = 90
$!VIEW FITSURFACES
#  CONSIDERBLANKING = YES
$!CONTOURLEVELS NEW
  CONTOURGROUP = 6
  RAWDATA
11
0
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9
1
$!GLOBALCONTOUR 6  COLORMAPFILTER{CONTINUOUSCOLOR{CMAX = 1}}
$!GLOBALCONTOUR 6  COLORMAPNAME = 'Diverging - Blue/Red'
$!GLOBALCONTOUR 6  LEGEND{ANCHORALIGNMENT = TOPCENTER}
$!GLOBALCONTOUR 6  LEGEND{XYPOS{X = 50}}
$!GLOBALCONTOUR 6  LEGEND{XYPOS{Y = 40}}
$!GLOBALCONTOUR 6  LEGEND{BOX{BOXTYPE = NONE}}
$!GLOBALCONTOUR 6  LEGEND{ISVERTICAL = NO}
$!THREEDVIEW VIEWWIDTH = 4.5

$!GLOBALCONTOUR 6  LEGEND{NUMBERTEXTSHAPE{HEIGHT = 2}}
$!GLOBALCONTOUR 6  LEGEND{HEADERTEXTSHAPE{HEIGHT = 2}}

$!THREEDAXIS FRAMEAXIS{XYPOS{Y = 35}}

$!GLOBALCONTOUR 6  COLORMAPFILTER{CONTINUOUSCOLOR{CMIN = 0.599999999999999978}}
$!CONTOURLEVELS NEW
  CONTOURGROUP = 6
  RAWDATA
9
0.6
0.65
0.7
0.75
0.8
0.85
0.9
0.95
1
$!REDRAWALL 

# use blanking
$!SLICEATTRIBUTES 2  OBEYSOURCEZONEBLANKING = YES
$!REDRAWALL 
$!VIEW FITSURFACES
$!THREEDVIEW VIEWWIDTH = 2.25

$!GLOBALCONTOUR 6  LEGEND{XYPOS{Y = 37}}

$!THREEDAXIS FRAMEAXIS{XYPOS{Y = 30.5}}
$!REDRAWALL 

$!PICK ADDALL
  SELECTTEXT = YES
$!PICK CLEAR

$!ATTACHTEXT
  ANCHORPOS
    {
    X = 5.0
    Y = 33.0
    }
  TEXTSHAPE
    {
    HEIGHT = 14
    ISBOLD = NO
    }
  COLOR = BLACK
  TEXT = 'tu<sub>*</sub>/H=|ndt%.3f|'

$!EXPORTSETUP EXPORTFNAME = '|OUTDIR|export_2_xz_ti_|NewNo%05d|.png'
$!EXPORT 
  EXPORTREGION = CURRENTFRAME
  
  

  
$!ALTERDATA 
  EQUATION = '{Q} = 0'

$!VarSet |NUMVARSINIT| = |NUMVARS|
$!VarSet |NUMVARSINIT| += 1

#$!PROMPTFORTEXTSTRING |U|
#INSTRUCTIONS = "Enter the variable number for U"
#$!PROMPTFORTEXTSTRING |V|
#INSTRUCTIONS = "Enter the variable number for V"
#$!PROMPTFORTEXTSTRING |W|
#INSTRUCTIONS = "Enter the variable number for W"

$!VarSet |U|=5
$!VarSet |V|=6
$!VarSet |W|=7
$!GLOBALTHREEDVECTOR UVAR = |U|
$!GLOBALTHREEDVECTOR VVAR = |V|
$!GLOBALTHREEDVECTOR WVAR = |W|


$!ALTERDATA 
  EQUATION = '{dudx} = ddx(u)'
$!ALTERDATA 
  EQUATION = '{dvdx} = ddx(v)'
$!ALTERDATA 
  EQUATION = '{dwdx} = ddx(w)'
$!ALTERDATA 
  EQUATION = '{dudy} = ddy(u)'
$!ALTERDATA 
  EQUATION = '{dvdy} = ddy(v)'
$!ALTERDATA 
  EQUATION = '{dwdy} = ddy(w)'
$!ALTERDATA 
  EQUATION = '{dudz} = ddz(u)'
$!ALTERDATA 
  EQUATION = '{dvdz} = ddz(v)'
$!ALTERDATA 
  EQUATION = '{dwdz} = ddz(w)'
$!ALTERDATA 
  EQUATION = '{s11} = {dudx}' 
$!ALTERDATA 
  EQUATION = '{s12} = 0.5*({dudy}+{dvdx})' 
$!ALTERDATA 
  EQUATION = '{s13} = 0.5*({dudz}+{dwdx})' 
$!ALTERDATA 
  EQUATION = '{s22} = {dvdy}' 
$!ALTERDATA 
  EQUATION = '{s23} = 0.5*({dvdz}+{dwdy})' 
$!ALTERDATA 
  EQUATION = '{s33} = {dwdz}' 
$!ALTERDATA 
  EQUATION = '{Omga12} = 0.5*({dudy}-{dvdx})' 
$!ALTERDATA 
  EQUATION = '{Omga13} = 0.5*({dudz}-{dwdx})' 
$!ALTERDATA 
  EQUATION = '{Omga23} = 0.5*({dvdz}-{dwdy})' 
#$!ALTERDATA 
#  EQUATION = '{s2o2_11} = {s11}**2 + {s12}**2 + {s13}**2 - {Omga12}**2 - {Omga13}**2' 
#$!ALTERDATA 
#  EQUATION = '{s2o2_12} = {s11}*{s12} + {s12}*{s22} + {s13}*{s23} - {Omga13}*{Omga23}' 
#$!ALTERDATA 
#  EQUATION = '{s2o2_13} = {s11}*{s13} + {s12}*{s23} + {s13}*{s33} - {Omga12}*{Omga23}' 
#$!ALTERDATA 
#  EQUATION = '{s2o2_22} = {s12}**2 + {s22}**2 + {s23}**2 - {Omga12}**2 - {Omga23}**2' 
#$!ALTERDATA 
#  EQUATION = '{s2o2_23} = {s12}*{s13} + {s22}*{s23} + {s23}*{s33} - {Omga12}*{Omga13}' 
#$!ALTERDATA 
#  EQUATION = '{s2o2_33} = {s13}**2 + {s23}**2 + {s33}**2 - {Omga13}**2 - {Omga23}**2'
$!ALTERDATA 
  EQUATION = '{Q} = 2*{Omga12}**2 + 2*{Omga13}**2 + 2*{Omga23}**2 - {S11}**2 - {S22}**2 - {S33}**2 - 2*{S12}**2 - 2*{S13}**2 - 2*{S23}**2'

$!VarSet |NUMVARSFIN| = |NUMVARS|
$!DELETEVARS [|NUMVARSINIT|-|NUMVARS|]


$!SETCONTOURVAR 
  VAR = 8
  CONTOURGROUP = 5
  LEVELINITMODE = RESETTONICE
$!CONTOURLEVELS NEW
  CONTOURGROUP = 5
  RAWDATA
11
-10
-8
-6
-4
-2
0
2
4
6
8
10
$!GLOBALCONTOUR 5  COLORMAPFILTER{COLORMAPDISTRIBUTION = CONTINUOUS}
$!GLOBALCONTOUR 5  COLORMAPFILTER{CONTINUOUSCOLOR{CMIN = -10}}
$!GLOBALCONTOUR 5  COLORMAPFILTER{CONTINUOUSCOLOR{CMAX = 10}}
$!GLOBALCONTOUR 5  COLORMAPNAME = 'Diverging - Blue/Red'
$!SLICEATTRIBUTES 2  SHOWGROUP = NO
$!SLICEATTRIBUTES 4  SHOWGROUP = YES
$!SLICEATTRIBUTES 4  SLICESURFACE = YPLANES
$!SLICEATTRIBUTES 4  CONTOUR{FLOODCOLORING = GROUP5}

$!GLOBALCONTOUR 5  LEGEND{ISVERTICAL = NO}
$!GLOBALCONTOUR 5  LEGEND{ANCHORALIGNMENT = TOPCENTER}
$!GLOBALCONTOUR 5  LEGEND{BOX{BOXTYPE = NONE}}
$!GLOBALCONTOUR 5  LEGEND{XYPOS{X = 50}}
$!GLOBALCONTOUR 5  LEGEND{XYPOS{Y = 40}}
$!GLOBALCONTOUR 5  LEGEND{NUMBERTEXTSHAPE{HEIGHT = 2}}
$!GLOBALCONTOUR 5  LEGEND{HEADERTEXTSHAPE{HEIGHT = 2}}


# use blanking
$!SLICEATTRIBUTES 4  OBEYSOURCEZONEBLANKING = YES
$!VIEW FITSURFACES
$!THREEDVIEW VIEWWIDTH = 2.25

$!GLOBALCONTOUR 5  LEGEND{XYPOS{Y = 37}}

$!GLOBALCONTOUR 5  COLORMAPFILTER{CONTINUOUSCOLOR{CMIN = -5}}
$!GLOBALCONTOUR 5  COLORMAPFILTER{CONTINUOUSCOLOR{CMAX = 5}}
$!CONTOURLEVELS NEW
  CONTOURGROUP = 5
  RAWDATA
11
-5
-4
-3
-2
-1
0
1
2
3
4
5
$!REDRAWALL 

$!REDRAWALL 
$!EXPORTSETUP EXPORTFNAME = '|OUTDIR|export_3_qxz_ti_|NewNo%05d|.png'
$!EXPORT 
  EXPORTREGION = CURRENTFRAME
  
  
$!GLOBALRGB REDCHANNELVAR = 4
$!GLOBALRGB GREENCHANNELVAR = 4
$!GLOBALRGB BLUECHANNELVAR = 4

$!SLICELAYERS SHOW = NO
$!ISOSURFACEATTRIBUTES 1  DEFINITIONCONTOURGROUP = 5
$!ISOSURFACEATTRIBUTES 1  ISOVALUE1 = 15
$!ISOSURFACELAYERS SHOW = YES

$!ISOSURFACEATTRIBUTES 1  CONTOUR{FLOODCOLORING = GROUP2}

$!THREEDVIEW VIEWERPOSITION{X = 170.980977192818671}
$!THREEDVIEW VIEWERPOSITION{Y = 92.5588849122314201}
$!THREEDVIEW VIEWERPOSITION{Z = 52.1949206143663673}
$!THREEDVIEW PSIANGLE = 59.9999999999999929
$!THREEDVIEW THETAANGLE = 239.999999999999972
$!REDRAWALL 
$!VIEW FITSURFACES
#  CONSIDERBLANKING = YES
  
$!ROTATE3DVIEW Z
  ANGLE = 160
  ROTATEORIGINLOCATION = DEFINEDORIGIN
$!REDRAWALL 
$!VIEW FITSURFACES
#  CONSIDERBLANKING = YES

$!THREEDVIEW VIEWWIDTH = 3.75

$!GLOBALCONTOUR 2  LEGEND{XYPOS{Y = 30}}
$!GLOBALCONTOUR 2  LEGEND{XYPOS{X = 70}}

# use blanking
$!ISOSURFACEATTRIBUTES 1  OBEYSOURCEZONEBLANKING = YES
$!FIELDMAP [2]  MESH{LINETHICKNESS = 0.40000000000000002}

$!THREEDVIEW VIEWERPOSITION{X = 18.470235627226742}
$!THREEDVIEW VIEWERPOSITION{Y = 10.707528970098444}
$!THREEDVIEW VIEWERPOSITION{Z = 12.056117301062443}
$!THREEDVIEW PSIANGLE = 59.999999999999993
$!THREEDVIEW THETAANGLE = 239.99999999999997

$!ROTATE3DVIEW Z
  ANGLE = 140
  ROTATEORIGINLOCATION = DEFINEDORIGIN
$!VIEW FITSURFACES
$!THREEDVIEW VIEWWIDTH = 2
$!REDRAWALL 



$!GLOBALCONTOUR 2  LEGEND{XYPOS{X = 50}}
$!GLOBALCONTOUR 2  LEGEND{XYPOS{Y = 40}}
$!GLOBALCONTOUR 2  LEGEND{SHOW = NO}

$!THREEDAXIS FRAMEAXIS{XYPOS{X = 75}}
$!THREEDAXIS FRAMEAXIS{XYPOS{Y = 25}}

$!ISOSURFACEATTRIBUTES 1  EFFECTS{USETRANSLUCENCY = YES}
$!ISOSURFACEATTRIBUTES 1  EFFECTS{SURFACETRANSLUCENCY = 50}

$!PICK ADDALL
  SELECTTEXT = YES
$!PICK CLEAR

$!ATTACHTEXT
  ANCHORPOS
    {
    X = 40.0
    Y = 22.0
    }
  TEXTSHAPE
    {
    HEIGHT = 14
    ISBOLD = NO
    }
  COLOR = BLACK
  TEXT = 'Q isosurface at tu<sub>*</sub>/H=|ndt%.3f|'
  
$!REDRAWALL 
$!EXPORTSETUP EXPORTFNAME = '|OUTDIR|export_4_qiso_ti_|NewNo%05d|.png'
$!EXPORT 
  EXPORTREGION = CURRENTFRAME

$!EndLoop
$!RemoveVar |MFBD|
